<?php
namespace core;
/**
 * please do not edit this file
 * you can add your routes to <b>routes.php</b> file below
 */
class Router{
    private static $getPaths=[];
    private static $postPaths=[];
    private static $args=[];

    /**
     * @param $pathIndication a string expression like /users/{d}
     * @param $callback callback or [Object,'methodName']
     * @return void
     */
    public static function get($pathIndication,$callback){
        self::$getPaths[$pathIndication]=$callback;
    }
    /**
     * @param $pathIndication a string expression like /users/{d}
     * @param $callback callback or [Object,'methodName']
     * @return void
     */
    public static function post($pathIndication,$callback){
        self::$postPaths[$pathIndication]=$callback;
    }
    private static function match($uriIndication,$requestPath){
        $uriIndication=preg_replace('#^/#','',$uriIndication);
        $uriIndication=preg_replace('#/$#','',$uriIndication);
        $requestPath=preg_replace('#^/#','',$requestPath);
        $requestPath=preg_replace('#/$#','',$requestPath);

        preg_match_all("#\{([^/]+)\}#",$uriIndication,$uriIndicationNames);
        $uriRegex=preg_replace("#\{([^/]+)\}#",'([^/]+)',$uriIndication);
        $uriRegex='#^'.$uriRegex.'$#';
        if(preg_match($uriRegex,$requestPath,$matches)){
            self::$args=[];
            for($i =1;$i<count($matches);$i++){
                $GLOBALS[$uriIndicationNames[1][$i-1]]=$matches[$i];
                self::$args[]=$matches[$i];
            }
            return true;
        }
        return false;
    }

    /**
     * processes the current incoming request and routes it to the corresponding function or class method
     * @return void
     * @throws Exception
     */
    public static function processIncomingRequest(){
        $foundRout=false;
        $requestUri=parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH);
        $paths=$_SERVER['REQUEST_METHOD']==='GET'?self::$getPaths:($_SERVER['REQUEST_METHOD']==='POST'?self::$postPaths:null);
        if($paths===null){
            throw new Exception('method not supported');
        }
        foreach ($paths as $uriIndication => $callback){
            if(self::match($uriIndication,$requestUri)){
                call_user_func_array($callback,self::$args);
                $foundRout=true;
            }
        }
        if(!$foundRout){
            //should redirect to 404 page
            require_once '../views/404.php';
        }
    }
}
